version: "3.3"

services:
  postgres:
    container_name: skadedb
    image: postgres:12.3-alpine
    env_file:
      - env/postgres.env
    volumes:
      - type: volume
        source: postgres_data
        target: /var/lib/postgresql/data
    ports:
      - target: 5432
        published: 5432
        
  skade:
    container_name: skade
    build:
      context: ./
      dockerfile: ./Docker/Dockerfile
    depends_on:
      - postgres
    ports:
      - target: 8080
        published: 8080


volumes:
  postgres_data:
