version: "3.3"

services:
  skade-db:
    container_name: skade-db
    image: postgres:12.3-alpine
    env_file:
      - env/postgres.env
    volumes:
      - type: volume
        source: postgres_data
        target: /var/lib/postgresql/data
    ports:
      - target: 5432
        published: 5432
        
  skade-api:
    container_name: skade-api
    build:
      context: ./
      dockerfile: ./backend/Docker/Dockerfile
    depends_on:
      - skade-db
    ports:
      - target: 8080
        published: 8080

  skade-frontend:
    container_name: skade-frontend
    build:
      context: ./frontend
      dockerfile: ./Docker/Dockerfile
    ports: 
      - target: 80
        published: 80
    stdin_open: true
    depends_on: 
      - skade-api

volumes:
  postgres_data:
